language: cpp
sudo: false
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  env:
    - CFLAGS="-g -O2 -Wsign-compare -Wall -Werror" 
  exclude:
    - os: osx
    - compiler: gcc

before_install:
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug ..
  - make
  - make ARGS='-V -j3' test
