language: cpp
sudo: false
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
    - compiler: gcc

before_install:
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug ..
  - make
  - ctest -D ExperimentalTest -V -j3
